name: JET

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  jet:
    name: JET - Julia latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
      - uses: julia-actions/cache@v2
      - name: Run JET
        shell: julia --color=yes --project=test/quality {0}
        run: |
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using DiversityAndDissimilarity
          using JET
          JET.test_package(DiversityAndDissimilarity; target_modules=(DiversityAndDissimilarity,))
